dist: xenial
sudo: required
language: c
cache: ccache
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

git:
  submodules: false

before_script:
  - sudo apt-get update -y
  - sudo apt-get install qemu-kvm libxen-dev libseccomp-dev -y
  - sudo apt-get install --only-upgrade binutils gcc -y
  - bash travis_wait.sh 60 git submodule update --init

env:
  - PLATFORM=solo5 MACHINE=x86_64 TESTS=spt EXTRAFLAGS=
  - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS=
  - PLATFORM=hw MACHINE=i486 ELF=elf TESTS=qemu EXTRAFLAGS='-- -F ACLFLAGS=-m32 -F ACLFLAGS=-march=i686'
  - PLATFORM=hw MACHINE=x86_64 TESTS=qemu EXTRAFLAGS= CXX='false'
  - PLATFORM=hw MACHINE=x86_64 TESTS=none KERNONLY=-k EXTRAFLAGS= 

script:
  - export CC=gcc-6
  - NOGCCERROR=1 ./build-rr.sh -o myobj -j16 -qq ${KERNONLY} ${PLATFORM} ${EXTRAFLAGS}
  - . ./myobj/config
  - ./tests/buildtests.sh ${KERNONLY}
  - ./tests/runtests.sh ${TESTS}


# touch me to force a travis rebuild
